[package]
name = "ibm-mq-snd"
version = "0.1.0"
authors = ["anatoly <anatolse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0"

[build-dependencies]
bindgen = "0"
